name: Format report
description: format bundle size report

inputs:
  bundleSizeOutput: 
    required: true
    description: bundle size report output


outputs:
  report: 
    description: output formatted message
    
runs:
  using: node16
  main: index.js

    