name: Bundle Analyzer
run-name: ${{ github.actor }} is testing out github action

on: 
  workflow_dispatch:
  pull_request:
    types: [opened,synchronize]

env: 
  build_dir: "build"

jobs:
  explore-github-action: 
    runs-on: ubuntu-22.04
    steps:
      - run: echo "hello world, the jobs automatically trigger by a ${{ github.event_name }} event."
      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: '18.17'

      - name: checkout git
        uses: actions/checkout@v4

      - name: setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: install deps
        run: pnpm install --no-frozen-lockfile

      - name: install bundlesize standalone deps
        run:  pnpm add -g @wpe-tkpd/bundlesize

      - name: build code
        run: pnpm build

      - name: bundle size
        run: pnpm bundle-size

      - name: get bundle size config
        id: config
        uses: ./.github/actions/bundle-size

      - name: format bundle size report 
        id: report
        uses: ./.github/actions/format-bundle-size-report
        with:
          bundleSizeOutput: ${{ steps.config.outputs.bundleSizeOutput }}
          

      - name: post bundle size report
        uses: actions/github-script@v6
        with:
          script: |
            const baseHeaders = {
              Accept: "application/vnd.github.v3+json",
              "Content-Type": "application/json",
              Authorization: `token ${{ secrets.GH_TOKEN }}`,
              "User-Agent": "tokopedia-lite-pull-request-bot",
            };

            const messageBody = `${{ steps.report.outputs.report }}`
            # const issueNumber = `${{ github.event.pull_request.number }}`

            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: messageBody
            })

      
      
      