name: action demo
run-name: is testing out github action
on: [push]
jobs:
  explore-github-action: 
    runs-on: ubuntu-22.04
    steps:
      - run: echo "hello world, the jobs automatically trigger by a ${{ github.event_name }} event."
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: '18.17'
      - run: npm -v
      